Repository horazont/aioxmpp, pull requests merged in 2020-04, with the labels that each got.

#314 muc: treat remote server unreachability like timeout self-ping
  aioxmpp/muc/self_ping.py
  tests/muc/test_self_ping.py
Labels: enhancement

#317 Implement JID escaping and unescaping functions
  aioxmpp/__init__.py
  aioxmpp/structs.py
  docs/api/changelog.rst
  docs/index.rst
  tests/test_structs.py
Labels: xep-implementation

#321 Add support for XEP-0308
  aioxmpp/__init__.py
  aioxmpp/misc/__init__.py
  aioxmpp/misc/lmc.py
  docs/api/changelog.rst
  docs/index.rst
  tests/misc/test_replace.py
Labels: enhancement, xep-implementation

#307 xso: fix assignment of enum members when only allow_coerce is true
  aioxmpp/xso/types.py
  docs/api/changelog.rst
  tests/xso/test_types.py
Labels: bug
